version: '3'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./xdebug.log:/tmp/xdebug.log
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Al final no creo q lo use.
  # Servidor NodeJs para comandos de laravel.
  nodejs:
    build:
      context: ./
      dockerfile: node.dockerfile
    working_dir: /var/www
    ports:
        - "3000:3000"
        - "3001:3001"
    volumes:
      - ../:/var/www

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # The Database
  database:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=cocoloco"
      - "MYSQL_DATABASE=getmeeting"
      - "MYSQL_USER=urslaravel"
      - "MYSQL_PASSWORD=passlaravel"

    ports:
        - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=database
     - PMA_USER=root
     - PMA_PASSWORD=cocoloco

    ports:
     - 8081:80
    volumes:
     - /sessions
    # Defino que phpmyadmin, depende de estos dos servicios, para q se inciie despues de ellos. No se garantizan que hayan terminado. (puede q realmente no haga falta)
    depends_on:
      - app
      - database

volumes:
  dbdata: